version: "3"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql"
      - "./config/my.cnf:/etc/mysql/conf.d/my.cnf"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci